# strongSwan 配置文件 (兼容 5.6.2 和 6.0.2)

charon {
    load_modular = yes
    plugins {
        include strongswan.d/charon/*.conf
        eap-radius {
            accounting = yes
            servers {
                radiusServer {
                    secret = FreeVPN@vpn5296
                    address = radius.sspacee.com
                    auth_port = 1812
                    acct_port = 1813
                }
            }
        }
    }
    
    filelog {
        charon {
            path = /var/log/strongswan.log
            time_format = %b %e %T
            ike_name = yes
            append = no
            default = 1
            flush_line = yes
        }
    }
    
    syslog {
        identifier = charon
        daemon {
            ike = 2
            knl = 2
        }
        auth {
            default = 2
        }
    }
    
    port = 500
    port_nat_t = 4500
    threads = 16
    retransmit_tries = 3
    retransmit_timeout = 4.0
    reauth_time = 0
    rekey_time = 4h
    rekey_bytes = 100m
    rekey_packets = 1000000
    close_action = none
    send_vendor_id = yes
}

include strongswan.d/*.conf